apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run:  account-balance-service
  name:  account-balance-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  account-balance-service
  template:
    metadata:
      labels:
        name:  account-balance-service
    spec:
      containers:
        - env:
            - name: server.port
              value: "8080"
            - name: spring.application.name
              value: "account-balance-service"
            - name: spring.data.redis.cluster.nodes
              value: gf-redis-server-0:6379
            - name: spring.data.redis.client-type
              value: JEDIS
            - name: spring.profiles.active
              value: redis
          #          - name: spring.data.gemfire.pool.locators
          #            valueFrom:
          #              configMapKeyRef:
          #                name: gemfire1-config
          #                key: locators
          image: cloudnativedata/account-balance-service:0.0.1-SNAPSHOT
          name: account-balance-service
#          imagePullPolicy: Always
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: account-balance-service
spec:
  selector:
    name: account-balance-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer