spring:
  application:
      name: account-balance
  cloud:
    function:
      definition: readBalanceFunction;paymentConsumer
    stream:
      http:
        GET: readBalanceFunction
        POST: paymentConsumer
      rabbit:
        default:
          requiredGroups: true
          dlqQuorum:
            enabled:  true
          quorum.enabled: true
          autoBindDlq: true
          prefetch: 10000
      bindings:
        readBalanceFunction-in-0:
          destination: readBalance
          group: ${spring.application.name}
#          consumer:
#            autoBindDlq: true
#            quorum.enabled: true
#            dlqQuorum:
#              enabled: true
#            prefetch: 10000
        readBalanceFunction-out-0:
          destination: balance
        paymentConsumer-in-0:
          destination: payments
          group: ${spring.application.name}

#          consumer:
#            autoBindDlq: true
#            quorum.enabled: true
#            dlqQuorum:
#              enabled: true
#            prefetch: 10000
  rabbitmq:
    username: rabbit